export const PRODUCT_REQUEST = "PRODUCT_REQUEST";
export const PRODUCT_SUCCESS = "PRODUCT_SUCCESS";
export const PRODUCT_UNSUCCESS = "PRODUCT_UNSUCCESS";
export const PRODUCT_ERROR = "PRODUCT_ERROR";
export const PRODUCT_DESTROY = "PRODUCT_DESTROY";

export const ORDER_REQUEST = "ORDER_REQUEST";
export const ORDER_SUCCESS = "ORDER_SUCCESS";
export const ORDER_UNSUCCESS = "ORDER_UNSUCCESS";
export const ORDER_ERROR = "ORDER_ERROR";
export const ORDER_DESTROY = "ORDER_DESTROY";


export const CARD_ADD = "CARD_ADD";
export const CARD_UPDATE = "CARD_UPDATE";
export const CARD_DELETE = "CARD_DELETE";
export const CARD_DESTROY = "CARD_DESTROY";